/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* ******************************************* START *********************************************** */
/* Libraries, Definitions and Global Declarations */
#include <stdint.h> // 							standard integer library
#include "main.h"
#include "user_keypad.h"

/* Superloop structure */
int main(void)
{
	/* Declarations and Initializations */
	USER_SystemClock_Config( ); // 				configure the system clock to 64 MHz
	USER_GPIO_Init( ); // 						initialize GPIOA pin 5 as output (for LD2)
	USER_Keypad_Init( ); //						initialize GPIOB pins 0-7 for keypad interfacing
    /* Repetitive block */
    for(;;){
    	GPIOA->ODR	^=	( 0x1UL <<  5U );//		value to toggle pin 5 of Port A (Toggle LD2)
    	USER_Delay_1sec( ); // 					delay function to create a visible blinking effect on LD2
    }
}

void USER_GPIO_Init( void ){
	RCC->APB2ENR |= ( 0x1UL << 2U );
	GPIOA->ODR &= ~( 0x1UL << 0U ); 
    GPIOA->ODR &= ~( 0x1UL << 1U ); 
    GPIOA->ODR &= ~( 0x1UL << 2U ); 
    GPIOA->ODR &= ~( 0x1UL << 3U );
	GPIOA->CRL &= ~( 0x3UL << 2U ) & ~( 0x2UL << 0U ); 
    GPIOA->CRL |= ( 0x1UL << 0U );                     
    GPIOA->CRL &= ~( 0x3UL << 6U ) & ~( 0x2UL << 4U );
    GPIOA->CRL |= ( 0x1UL << 4U );
    GPIOA->CRL &= ~( 0x3UL << 10U ) & ~( 0x2UL << 8U );
    GPIOA->CRL |= ( 0x1UL << 8U );
    GPIOA->CRL &= ~( 0x3UL << 14U ) & ~( 0x2UL << 12U );
    GPIOA->CRL |= ( 0x1UL << 12U );
}

void USER_SystemClock_Config( void ){
	FLASH->ACR	&=	~( 0x5UL <<  0U );//		two wait states latency, if SYSCLK > 48MHz
	FLASH->ACR	|=	 ( 0x2UL <<  0U );//		two wait states latency, if SYSCLK > 48MHz
	RCC->CFGR	&=	~( 0x1UL << 16U )//			PLL HSI oscillator clock /2 selected as PLL input clock
				&	~( 0x7UL << 11U )// 		APB2 prescaler /1
				&	~( 0x3UL <<  8U );// 		APB1 prescaler /2
	RCC->CFGR	|=	 ( 0xFUL << 18U )//			PLL input clock x 16 (PLLMUL bits)
				|	 ( 0x4UL <<  8U );//		APB1 prescaler /2
	RCC->CR		|=	 ( 0x1UL << 24U );//		PLL2 ON
	while( !(RCC->CR & ~( 0x1UL << 25U )));//	wait until PLL is locked
	RCC->CFGR	&=	~( 0x1UL << 0U  );//		PLL used as system clock (SW bits)
	RCC->CFGR	|=	 ( 0x2UL << 0U  );//		PLL used as system clock (SW bits)
	while( 0x8UL != ( RCC->CFGR & 0xCUL ));//	wait until PLL is switched
}

void USER_Delay_1sec( void ){
	__asm(" 		ldr r0, =7111111UL	");//	load the value to be used as delay count
	__asm(" again:	sub r0, r0, #1		");//	decrement the delay count
	__asm("			cmp r0, #0			");//	check if the delay count has reached zero
	__asm("			bne again			");//	if not, repeat the process
	__asm("			nop					");//	no operation (to ensure exact timing)
}

void USER_Keypad_Init();
uint8_t USER_Key();
